edit 13

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -85,14 +85,14 @@ jobs:
       - name: Purge OpenAI Resource
         if: success()
         run: |
-                    # Purge OpenAI Resource
-                echo "Purging the OpenAI Resource..."
-                if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/westus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
-                    echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
-                else
-                    echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
-                fi            
-
+            # Purge OpenAI Resource
+            echo "Purging the OpenAI Resource..."
+            if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/westus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
+                echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+            else
+                echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+            fi
+  
         
     #   - name: Send Notification on Failure
     #     if: failure()
